version: '2'

services:
  kafka:
    image: 'landoop/fast-data-dev:latest'
    environment:
      ADV_HOST: localhost
    ports:
      - '2181:2181'
      - '3030:3030'
      - '8081-8083:8081-8083'
      - '9581-9585:9581-9585'
      - '9092:9092'
